### ISSUE TITLE
Recyclerview mismatch 

### ISSUE THREAD

**Issue by rajumark** [pwittchen/InfiniteScroll#17]
![Screen Shot 2019-05-27 at 2 54 30 PM](https://user-images.githubusercontent.com/24580643/58410264-76018300-808f-11e9-8ce8-af0907df0d45.png)

**Comment by pwittchen** [comment]
Hi,

It looks like you're using android support library instead anroidx, which is the latest and recommended dependency. You can replace support library with `androidx.appcompat:appcompat:latest_version` in your dependency list. If for some reason, you need or want to you support library you can use` 0.0.1` version of the library (instead of `0.0.2`), which uses support libraries under the hood.

Regards,
Piotr

**Comment by pwittchen** [comment]
Did my suggestions solve your issue @rajumark?

**Comment by rajumark** [comment]
Yes , thanks a lot

**Comment by pwittchen** [comment]
Ok, great.
